on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev
  workflow_dispatch:

name: Lint, Tests and Build

jobs:
  test:
    name: Lint, Tests And Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - run: bun install
      - run: bun run format
      - run: bun run build
